<?php
$BibleBooks = [
"-1513" => ["content" => "Genèse: fin rédaction"],
"-1512" => ["content" => "Exode: fin rédaction"],
"-1512" => ["content" => "Lévitique: fin rédaction"],
"-1473" => ["content" => "Nombres: fin rédaction"],
"-1473" => ["content" => "Deutéronome: fin rédaction"],
"-1450" => ["content" => "Josué: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"-1100" => ["content" => "Juges: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"-1090" => ["content" => "Ruth: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"-1078" => ["content" => "1 Samuel: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"-1040" => ["content" => "2 Samuel: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"-0580" => ["content" => "1 Rois: fin rédaction"],
"-0580" => ["content" => "2 Rois: fin rédaction"],
"-0460" => ["content" => "1 Chroniques: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"-0460" => ["content" => "2 Chroniques: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"-0460" => ["content" => "Esdras: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"-0443" => ["content" => "Néhémie: fin rédaction",  "className" => "approximatedEnd"],
"-0475" => ["content" => "Esther: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"-1473" => ["content" => "Job: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"-0460" => ["content" => "Psaumes: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"-0717" => ["content" => "Proverbes: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"-1000" => ["content" => "Ecclésiaste: fin rédaction",  "className" => "approximatedStart"],
"-1020" => ["content" => "Chant de Salomon: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"-0732" => ["content" => "Isaïe: fin rédaction",  "className" => "approximatedEnd"],
"-0580" => ["content" => "Jérémie: fin rédaction"],
"-0607" => ["content" => "Lamentations: fin rédaction"],
"-0591" => ["content" => "Ézéchiel: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"-0536" => ["content" => "Daniel: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"-0745" => ["content" => "Osée: fin rédaction",  "className" => "approximatedEnd"],
"-0820" => ["content" => "Joël: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"-0804" => ["content" => "Amos: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"-607" => ["content" => "Abdias: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"-0844" => ["content" => "Jonas: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"-0717" => ["content" => "Michée: fin rédaction",  "className" => "approximatedStart"],
"-0632" => ["content" => "Nahum: fin rédaction",  "className" => "approximatedStart"],
"-0628" => ["content" => "Habacuc: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"-0648" => ["content" => "Sophonie: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"-0520" => ["content" => "Aggée: fin rédaction"],
"-0518" => ["content" => "Zacharie: fin rédaction"],
"-0443" => ["content" => "Malachie: fin rédaction",  "className" => "approximatedEnd"],
"0041" => ["content" => "Matthieu: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"0060" => ["content" => "Marc: fin rédaction",  "className" => "approximatedStart approximatedEnd",  "end" => "0065"],
"0056" => ["content" => "Luc: fin rédaction",  "className" => "approximatedStart approximatedEnd",  "end" => "0058"],
"0098" => ["content" => "Jean: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"0061" => ["content" => "Actes: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"0056" => ["content" => "Romains: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"0055" => ["content" => "1 Corinthiens: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"0055" => ["content" => "2 Corinthiens: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"0050" => ["content" => "Galates: fin rédaction",  "className" => "approximatedStart approximatedEnd",  "end" => "0052"],
"0060" => ["content" => "Éphésiens: fin rédaction",  "className" => "approximatedStart approximatedEnd",  "end" => "0061"],
"0060" => ["content" => "Philippiens: fin rédaction",  "className" => "approximatedStart approximatedEnd",  "end" => "0061"],
"0060" => ["content" => "Colossiens: fin rédaction",  "className" => "approximatedStart approximatedEnd",  "end" => "0061"],
"0050" => ["content" => "1 Thessaloniciens: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"0051" => ["content" => "2 Thessaloniciens: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"0061" => ["content" => "1 Timothée: fin rédaction",  "className" => "approximatedStart approximatedEnd",  "end" => "0064"],
"0065" => ["content" => "2 Timothée: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"0061" => ["content" => "Tite: fin rédaction",  "className" => "approximatedStart approximatedEnd",  "end" => "0064"],
"0060" => ["content" => "Philémon: fin rédaction",  "className" => "approximatedStart approximatedEnd",  "end" => "0061"],
"0061" => ["content" => "Hébreux: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"0062" => ["content" => "Jacques: fin rédaction",  "className" => "approximatedStart"],
"0062" => ["content" => "1 Pierre: fin rédaction",  "className" => "approximatedStart approximatedEnd",  "end" => "0064"],
"0064" => ["content" => "2 Pierre: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"0098" => ["content" => "1 Jean: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"0098" => ["content" => "2 Jean: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"0098" => ["content" => "3 Jean: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"0065" => ["content" => "Jude: fin rédaction",  "className" => "approximatedStart approximatedEnd"],
"0096" => ["content" => "Révélation: fin rédaction",  "className" => "approximatedStart approximatedEnd"]
];?>